ramen: broth::message::Message Class Reference
broth::message::Message Class Reference
Class that is used to create messages that will be sent between mesh nodes and serializing these messages.
#include <message.hpp>
Public Member Functions
~Message ()
Destroy the Message object.
Message (MessageType type, uint32_t term)
Construct a new Message object.
void addFields (uint32_t last_log_term, uint32_t last_log_index)
MessageRequestVote.
void addFields (bool granted)
MessageSendVote.
void addFields (uint32_t previous_log_index, uint32_t previous_log_term, string_t entries, uint32_t commit_index)
MessageRequestAppendEntry.
void addFields (bool success, uint32_t match_index)
MessageRespondAppendEntry.
void addFields (string_t data, bool ack)
DistributeEntry.
void addFields (uint32_t message_id, bool ack)
DistributeEntryAck.
string_t serialize ()
Serializes the current message object to a JSON string.
Private Attributes
string_t _serialized_payload
MessageType _message_type
uint32_t _term
DynamicJsonDocument * _payload
std::map< string_t, uint32_t > _field_uint32_t
std::map< string_t, bool > _field_bool
std::map< string_t, string_t > _field_string_t
Detailed Description
Class that is used to create messages that will be sent between mesh nodes and serializing these messages.
Definition at line 36 of file message.hpp.
Constructor & Destructor Documentation
~Message()
_message::~Message ()
Destroy the Message object.
Definition at line 16 of file message.cpp.
Message()
_message::Message (MessageType type, uint32_t term)
Construct a new Message object.
Parameters
type Message type to initialize
term Current term of the node
Definition at line 11 of file message.cpp.
Member Function Documentation
addFields() [1/6]
void broth::message::Message::addFields (bool granted) inline
MessageSendVote.
Parameters
granted
Definition at line 85 of file message.hpp.
addFields() [2/6]
void broth::message::Message::addFields (bool success, uint32_t match_index) inline
MessageRespondAppendEntry.
Parameters
success
match_index
Definition at line 125 of file message.hpp.
addFields() [3/6]
void broth::message::Message::addFields (string_t data, bool ack) inline
DistributeEntry.
Parameters
data
Definition at line 142 of file message.hpp.
addFields() [4/6]
void broth::message::Message::addFields (uint32_t last_log_term, uint32_t last_log_index) inline
MessageRequestVote.
Parameters
last_log_term
last_log_index
Definition at line 68 of file message.hpp.
Referenced by broth::server::Server::handleAppendEntriesRequest(), broth::server::Server::handleVoteRequest(), broth::server::Server::moveDataFromQueueToLog(), broth::server::Server::requestAppendEntries(), broth::server::Server::requestVote(), and broth::server::Server::sendLocalQueueDataToLeaderQueue().
addFields() [5/6]
void broth::message::Message::addFields (uint32_t message_id, bool ack) inline
DistributeEntryAck.
Parameters
ack
Definition at line 159 of file message.hpp.
addFields() [6/6]
void broth::message::Message::addFields (uint32_t previous_log_index, uint32_t previous_log_term, string_t entries, uint32_t commit_index) inline
MessageRequestAppendEntry.
Parameters
previous_log_index
previous_log_term
entries
commit_index
Definition at line 102 of file message.hpp.
serialize()
string_t _message::serialize ()
Serializes the current message object to a JSON string.
Returns
string_t
Definition at line 20 of file message.cpp.
Referenced by broth::server::Server::handleAppendEntriesRequest(), broth::server::Server::handleVoteRequest(), broth::server::Server::moveDataFromQueueToLog(), broth::server::Server::requestAppendEntries(), broth::server::Server::requestVote(), and broth::server::Server::sendLocalQueueDataToLeaderQueue().
Member Data Documentation
_field_bool
std::map<string_t, bool> broth::message::Message::_field_bool private
Definition at line 44 of file message.hpp.
_field_string_t
std::map<string_t, string_t> broth::message::Message::_field_string_t private
Definition at line 45 of file message.hpp.
_field_uint32_t
std::map<string_t, uint32_t> broth::message::Message::_field_uint32_t private
Definition at line 43 of file message.hpp.
_message_type
MessageType broth::message::Message::_message_type private
Definition at line 39 of file message.hpp.
_payload
DynamicJsonDocument* broth::message::Message::_payload private
Definition at line 41 of file message.hpp.
_serialized_payload
string_t broth::message::Message::_serialized_payload private
Definition at line 38 of file message.hpp.
_term
uint32_t broth::message::Message::_term private
Definition at line 40 of file message.hpp.
The documentation for this class was generated from the following files:
/ramen/library/src/ramen/message.hpp
/ramen/library/src/ramen/message.cpp