ramen: ramen::logholder::LogHolder Class Reference
ramen::logholder::LogHolder Class Reference
Holds the logs of the consensus for the given server.
#include <log_holder.hpp>
Public Member Functions
LogHolder ()
Construct a new Log Holder object.
uint32_t getMatchIndex (uint32_t address)
Get the Match Index object.
void setMatchIndex (uint32_t address, uint32_t index)
Set the Match Index object.
uint32_t getNextIndex (uint32_t address)
Get the Next Index object.
void setNextIndex (uint32_t address, uint32_t index)
Set the Next Index object.
void advanceCommitIndex (uint32_t address)
void resetMatchIndexMap (std::list< uint32_t > *node_list_ptr)
Set the match index for all nodes to 0.
void resetNextIndexMap (std::list< uint32_t > *node_list_ptr)
Set the next index for all nodes to 1.
uint32_t getLogSize ()
Get the size of the entries.
uint32_t getLastLogTerm ()
Get the last log entry's term.
Private Attributes
std::vector< std::pair< uint32_t, string_t > > _entries
std::unordered_map< uint32_t, uint32_t > * _match_index_ptr = NULL
std::unordered_map< uint32_t, uint32_t > * _next_index_ptr = NULL
Detailed Description
Holds the logs of the consensus for the given server.
Definition at line 22 of file log_holder.hpp.
Constructor & Destructor Documentation
LogHolder::LogHolder ()
Construct a new Log Holder object.
Definition at line 10 of file log_holder.cpp.
Member Function Documentation
void LogHolder::advanceCommitIndex (uint32_t address)
Parameters
address
Definition at line 26 of file log_holder.cpp.
uint32_t LogHolder::getLastLogTerm ()
Get the last log entry's term.
Returns
uint32_t
Definition at line 48 of file log_holder.cpp.
Referenced by ramen::server::Server::requestVote().
uint32_t LogHolder::getLogSize ()
Get the size of the entries.
Returns
uint32_t
Definition at line 44 of file log_holder.cpp.
Referenced by ramen::server::Server::requestVote().
uint32_t LogHolder::getMatchIndex (uint32_t address)
Get the Match Index object.
Parameters
address
Returns
uint32_t
Definition at line 12 of file log_holder.cpp.
uint32_t LogHolder::getNextIndex (uint32_t address)
Get the Next Index object.
Parameters
address
Returns
uint32_t
Definition at line 19 of file log_holder.cpp.
void LogHolder::resetMatchIndexMap (std::list< uint32_t > * node_list_ptr)
Set the match index for all nodes to 0.
Parameters
nodeList Node list obtained from painlessMesh
Definition at line 28 of file log_holder.cpp.
Referenced by ramen::server::Server::startNewElection().
void LogHolder::resetNextIndexMap (std::list< uint32_t > * node_list_ptr)
Set the next index for all nodes to 1.
Parameters
nodeList Node list obtained from painlessMesh
Definition at line 36 of file log_holder.cpp.
Referenced by ramen::server::Server::startNewElection().
void LogHolder::setMatchIndex (uint32_t address, uint32_t index)
Set the Match Index object.
Parameters
address
index
Definition at line 17 of file log_holder.cpp.
void LogHolder::setNextIndex (uint32_t address, uint32_t index)
Set the Next Index object.
Parameters
address
index
Definition at line 24 of file log_holder.cpp.
Member Data Documentation
std::vector<std::pair<uint32_t, string_t> > ramen::logholder::LogHolder::_entries private
Definition at line 24 of file log_holder.hpp.
Referenced by getLastLogTerm(), and getLogSize().
std::unordered_map<uint32_t, uint32_t>* ramen::logholder::LogHolder::_match_index_ptr = NULL private
Definition at line 26 of file log_holder.hpp.
Referenced by resetMatchIndexMap().
std::unordered_map<uint32_t, uint32_t>* ramen::logholder::LogHolder::_next_index_ptr = NULL private
Definition at line 27 of file log_holder.hpp.
Referenced by resetNextIndexMap().
The documentation for this class was generated from the following files:
/ramen/library/src/ramen/log_holder.hpp
/ramen/library/src/ramen/log_holder.cpp